# Generated by Django 3.0.3 on 2020-05-31 09:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('option1', models.IntegerField(blank=True, null=True)),
                ('option2', models.IntegerField(blank=True, null=True)),
                ('option3', models.IntegerField(blank=True, null=True)),
                ('option4', models.IntegerField(blank=True, null=True)),
                ('applied', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
