# Generated by Django 3.0.3 on 2020-05-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='choose1',
            field=models.CharField(default='default option1', max_length=50),
        ),
        migrations.AddField(
            model_name='votes',
            name='choose2',
            field=models.CharField(default='default option2', max_length=50),
        ),
        migrations.AddField(
            model_name='votes',
            name='choose3',
            field=models.CharField(default='default option3', max_length=50),
        ),
        migrations.AddField(
            model_name='votes',
            name='choose4',
            field=models.CharField(default='default option4', max_length=50),
        ),
    ]
