# Generated by Django 3.0.3 on 2020-05-31 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20200531_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 20, 18, 26, 969346)),
        ),
    ]
