# Generated by Django 3.0.3 on 2020-05-31 16:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0003_auto_20200531_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 22, 3, 48, 80036)),
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('choose1', models.CharField(default='default option1', max_length=50)),
                ('option1', models.IntegerField(blank=True, null=True)),
                ('choose2', models.CharField(default='default option2', max_length=50)),
                ('option2', models.IntegerField(blank=True, null=True)),
                ('choose3', models.CharField(default='default option3', max_length=50)),
                ('option3', models.IntegerField(blank=True, null=True)),
                ('choose4', models.CharField(default='default option4', max_length=50)),
                ('option4', models.IntegerField(blank=True, null=True)),
                ('applied', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 5, 31, 22, 3, 48, 81034))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
