# Generated by Django 3.0.3 on 2020-05-31 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20200531_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 1, 3, 42, 872365)),
        ),
        migrations.AlterField(
            model_name='votes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
